services:
  postgres:
    image: postgres:17.2-alpine
    container_name: fincraft_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fincraft_user
      POSTGRES_PASSWORD: fincraft_password
      POSTGRES_DB: fincraft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fincraft_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
